plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.hoteldelvalle.kiosco'
    compileSdk 34

    defaultConfig {
        applicationId "com.hoteldelvalle.kiosco"
        minSdk 23
        targetSdk 34
        versionCode 29
        versionName "1.1.0"
    }

    signingConfigs {
        release {
            def props = new Properties()
            file("/home/CyHotel/keys/keystore.properties").withInputStream { props.load(it) }
            storeFile file(props['KEYSTORE'])
            storePassword props['KS_PASS']
            keyAlias props['KEY_ALIAS']
            keyPassword props['KEY_PASS']
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
}
